# Generated by Django 4.2.7 on 2023-11-30 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='keycloak_id',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
